<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="BLACKPANTHER" failures="2" tests="13" name="Test" time="37.062" errors="0" timestamp="2025-04-09T15:27:09 IST">
  <testcase classname="Tests.Regression" name="validate_date" time="0.451"/>
  <testcase classname="Tests.Regression" name="alert_handling" time="1.993"/>
  <testcase classname="Tests.ErrorValidation" name="validate_country_name" time="2.643">
    <skipped/>
  </testcase> <!-- validate_country_name -->
  <testcase classname="Tests.Regression" name="switch_window" time="2.142"/>
  <testcase classname="Tests.ErrorValidation" name="validate_country_name" time="2.178">
    <failure type="java.lang.AssertionError" message="expected [null] but found [Indian]">
      <![CDATA[java.lang.AssertionError: expected [null] but found [Indian]
at Tests.ErrorValidation.validate_country_name(ErrorValidation.java:22)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- validate_country_name -->
  <testcase classname="Tests.DataValidation" name="validate_country_name" time="2.584"/>
  <testcase classname="Tests.ErrorValidation" name="validate_country_name" time="2.899">
    <skipped/>
  </testcase> <!-- validate_country_name -->
  <testcase classname="Tests.DataValidation" name="validate_country_name" time="2.325"/>
  <testcase classname="Tests.ErrorValidation" name="validate_country_name" time="2.915">
    <failure type="java.lang.AssertionError" message="expected [null] but found [USA]">
      <![CDATA[java.lang.AssertionError: expected [null] but found [USA]
at Tests.ErrorValidation.validate_country_name(ErrorValidation.java:22)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- validate_country_name -->
  <testcase classname="Tests.DataValidation" name="validate_country_name" time="1.928"/>
  <testcase classname="Tests.DataValidation" name="add_entries" time="1.316"/>
  <testcase classname="Tests.DataValidation" name="add_entries" time="0.928"/>
  <testcase classname="Tests.DataValidation" name="add_entries" time="0.762"/>
</testsuite> <!-- Test -->
